--
-- PostgreSQL database dump

-- Name: ASSORTMENT; Type: TABLE; Schema: public; Owner: prod_sova
--

CREATE TABLE public."ASSORTMENT" (
    id integer NOT NULL,
    header_text text NOT NULL,
    description_text text
);


ALTER TABLE public."ASSORTMENT" OWNER TO prod_sova;

--
-- Name: ASSORTMENT_id_seq; Type: SEQUENCE; Schema: public; Owner: prod_sova
--

ALTER TABLE public."ASSORTMENT" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ASSORTMENT_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999999
    CACHE 1
);


--
-- Name: DAMPERS_LIST; Type: TABLE; Schema: public; Owner: prod_sova
--

CREATE TABLE public."DAMPERS_LIST" (
    id integer NOT NULL,
    text text NOT NULL
);


ALTER TABLE public."DAMPERS_LIST" OWNER TO prod_sova;

--
-- Name: DAMPERS_LIST_id_seq; Type: SEQUENCE; Schema: public; Owner: prod_sova
--

ALTER TABLE public."DAMPERS_LIST" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DAMPERS_LIST_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 9999999
    CACHE 1
);


--
-- Name: SLIDER_IMG; Type: TABLE; Schema: public; Owner: prod_sova
--

CREATE TABLE public."SLIDER_IMG" (
    id integer NOT NULL,
    ref character varying NOT NULL,
    inner_text character varying
);


ALTER TABLE public."SLIDER_IMG" OWNER TO prod_sova;

--
-- Name: SLIDER_IMG_id_seq; Type: SEQUENCE; Schema: public; Owner: prod_sova
--

ALTER TABLE public."SLIDER_IMG" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SLIDER_IMG_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 99999999
    CACHE 1
);


--
-- Name: TOP_INFO; Type: TABLE; Schema: public; Owner: prod_sova
--

CREATE TABLE public."TOP_INFO" (
    id bigint NOT NULL,
    rec_order integer NOT NULL,
    rec_text text NOT NULL,
    is_phone integer DEFAULT 0 NOT NULL,
    is_bold integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."TOP_INFO" OWNER TO prod_sova;

--
-- Name: TOP_INFO_id_seq; Type: SEQUENCE; Schema: public; Owner: prod_sova
--

ALTER TABLE public."TOP_INFO" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TOP_INFO_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999999999999999
    CACHE 1
);


--
-- Name: TOP_INFO_rec_order_seq; Type: SEQUENCE; Schema: public; Owner: prod_sova
--

ALTER TABLE public."TOP_INFO" ALTER COLUMN rec_order ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TOP_INFO_rec_order_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 999999999
    CACHE 1
);


--
-- Name: USERS; Type: TABLE; Schema: public; Owner: prod_sova
--

CREATE TABLE public."USERS" (
    id integer NOT NULL,
    login character varying NOT NULL,
    password character varying NOT NULL
);


ALTER TABLE public."USERS" OWNER TO prod_sova;

--
-- Name: USERS_id_seq; Type: SEQUENCE; Schema: public; Owner: prod_sova
--

ALTER TABLE public."USERS" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."USERS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 99999999
    CACHE 1
);


--
-- Name: ASSORTMENT Assortment_List_pkey; Type: CONSTRAINT; Schema: public; Owner: prod_sova
--

ALTER TABLE ONLY public."ASSORTMENT"
    ADD CONSTRAINT "Assortment_List_pkey" PRIMARY KEY (id);


--
-- Name: DAMPERS_LIST DAMPERS_LIST_pkey; Type: CONSTRAINT; Schema: public; Owner: prod_sova
--

ALTER TABLE ONLY public."DAMPERS_LIST"
    ADD CONSTRAINT "DAMPERS_LIST_pkey" PRIMARY KEY (id);


--
-- Name: SLIDER_IMG SLIDER_IMG_pkey; Type: CONSTRAINT; Schema: public; Owner: prod_sova
--

ALTER TABLE ONLY public."SLIDER_IMG"
    ADD CONSTRAINT "SLIDER_IMG_pkey" PRIMARY KEY (id);


--
-- Name: TOP_INFO TOP_INFO_TABLE_pkey; Type: CONSTRAINT; Schema: public; Owner: prod_sova
--

ALTER TABLE ONLY public."TOP_INFO"
    ADD CONSTRAINT "TOP_INFO_TABLE_pkey" PRIMARY KEY (id);


--
-- Name: USERS USERS_pkey; Type: CONSTRAINT; Schema: public; Owner: prod_sova
--

ALTER TABLE ONLY public."USERS"
    ADD CONSTRAINT "USERS_pkey" PRIMARY KEY (id);


--
-- Name: TABLE "ASSORTMENT"; Type: ACL; Schema: public; Owner: prod_sova
--

GRANT ALL ON TABLE public."ASSORTMENT" TO prod_sova;


--
-- Name: TABLE "DAMPERS_LIST"; Type: ACL; Schema: public; Owner: prod_sova
--

GRANT ALL ON TABLE public."DAMPERS_LIST" TO prod_sova;


--
-- Name: TABLE "SLIDER_IMG"; Type: ACL; Schema: public; Owner: prod_sova
--

GRANT ALL ON TABLE public."SLIDER_IMG" TO prod_sova;


--
-- Name: TABLE "TOP_INFO"; Type: ACL; Schema: public; Owner: prod_sova
--

GRANT ALL ON TABLE public."TOP_INFO" TO prod_sova;


--
-- Name: TABLE "USERS"; Type: ACL; Schema: public; Owner: prod_sova
--

GRANT ALL ON TABLE public."USERS" TO prod_sova;


--
-- PostgreSQL database dump complete
--
